version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATABASE_NAME}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3304:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    image: openjdk:17-jdk-alpine
    container_name: springboot-container
    depends_on:
      - mysql
    volumes:
      - ./target/your-app.jar:/app.jar
    command: [ "java", "-jar", "/app.jar" ]
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"

volumes:
  mysql_data: